// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kpr_project.Models;

namespace kpr_project.Migrations
{
    [DbContext(typeof(kprContext))]
    partial class kprContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kpr_project.Models.SkemaDetail", b =>
                {
                    b.Property<Guid>("Iddetail")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Bulan");

                    b.Property<decimal>("Bunga");

                    b.Property<decimal>("PelunasanPokok");

                    b.Property<decimal>("Pokok");

                    b.Property<decimal>("SisaPokok");

                    b.Property<decimal>("Tagihan");

                    b.HasKey("Iddetail");

                    b.ToTable("SkemaDetail");
                });

            modelBuilder.Entity("kpr_project.Models.SkemaKpr", b =>
                {
                    b.Property<Guid>("Idskema")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Bunga");

                    b.Property<decimal>("Dp");

                    b.Property<decimal>("Harga");

                    b.Property<int>("Tenor");

                    b.HasKey("Idskema");

                    b.ToTable("SkemaKpr");
                });
#pragma warning restore 612, 618
        }
    }
}
